baseURL = 'https://mg-truth.plus360.eu/'
languageCode = 'ru'
title = 'Матвей Ганопольский: YouTube канал "Ганапольская правда", книги, новости'

disableKinds = ["taxonomy", "term", ]
ignoreFiles = ['/book-shop']
[params]
    description = "Проекты Матвея Ганапольского. Узнайте о его информационных и развлекательных проектах, смотрите видео с YouTube и поддержите автора"
    logoName = "Ганапольская правда"
    heroTitle = [
        "Информационные, аналитические и развлекательные проекты",
        "Матвея Ганопольского"
        ]
    [params.googleSheet]
        donateURL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwu-hrqAQHqcOvq5VRanJz1PiKjrCp0nft2WdMDVIIee2dQ5zOVQqdqbeRXIC6I904CK3YyPYJYNp8/pub?gid=0&single=true&output=csv"

    [params.youtube]
        # feedURL = "http://localhost:8787/"
        channelUrl = "https://www.youtube.com/@Ganapolsky"
        feedURL = "https://yt-api-proxy.kolya-ya.workers.dev/"
        channelId = "UCA_2oV10_uipWBWlyfJj16w"  # channel ID
        maxResults = 10
    [params.shop]
        shopIsEnabled = false

[menu]
    [[menu.top]]
        name = "YouTube"
        weight = 4
        identifier = "youtube"
        url = "https://www.youtube.com/@Ganapolsky"

[HTTPCache]
  [HTTPCache.cache]
    [HTTPCache.cache.for]
      excludes = ['**']
      includes = []