baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MG truth'

disableKinds = ["taxonomy", "term", ]
ignoreFiles = ['/book-shop']
[params]
    logoName = "MatGun Truth"
    heroTitle = [
        "Информационные и развлекательные проекты",
        "Матвея Ганопольского"
        ]

    [params.youtube]
        feedURL = "http://localhost:8787/"
        channelId = "UCA_2oV10_uipWBWlyfJj16w"  # channel ID
        playListsIds = [
            "PLnPDytUjzMjorEFqrGw5xZmf_WEfip1WP", # Ганапольская правда
            "PLnPDytUjzMjqVgdw4DZkWlphQaWpTFBU6", # В рабочий полдень
            # "PLnPDytUjzMjoitAJlTHBEvAIVoV3iQUU-", # Ганапольское радио
        ]
        max_videos = 50  # Max qty of videos to show

[menu]
    [[menu.top]]
        name = "YouTube"
        weight = 4
        identifier = "youtube"
        url = "/youtube/"

    [[menu.top]]
        name = "Donate"
        weight = 17
        identifier = "donate"
        url = "/donate/"