baseURL = 'https://example.org/'
languageCode = 'ru'
title = 'MG truth'

disableKinds = ["taxonomy", "term", ]
ignoreFiles = ['/book-shop']
[params]
    logoName = "Ганапольская правда"
    heroTitle = [
        "Информационные, аналитические и развлекательные проекты",
        "Матвея Ганопольского"
        ]
    [params.googleSheet]
        donateURL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwu-hrqAQHqcOvq5VRanJz1PiKjrCp0nft2WdMDVIIee2dQ5zOVQqdqbeRXIC6I904CK3YyPYJYNp8/pub?gid=0&single=true&output=csv"

    [params.youtube]
        # feedURL = "http://localhost:8787/"
        channelUrl = "https://www.youtube.com/@Ganapolsky"
        feedURL = "https://yt-api-proxy.kolya-ya.workers.dev/"
        channelId = "UCA_2oV10_uipWBWlyfJj16w"  # channel ID
        maxResults = 13
        [[params.youtube.playLists]]
            name = "Ганапольская правда"
            id = "PLnPDytUjzMjorEFqrGw5xZmf_WEfip1WP"
        [[params.youtube.playLists]]
            name = "В рабочий полдень"
            id = "PLnPDytUjzMjqVgdw4DZkWlphQaWpTFBU6"
        # [[params.youtube.playLists]]
        #     name = "Ганапольское радио"
        #     id = "PLnPDytUjzMjoitAJlTHBEvAIVoV3iQUU-"
        # playListsIds = [
        #     "PLnPDytUjzMjorEFqrGw5xZmf_WEfip1WP", # Ганапольская правда
        #     "PLnPDytUjzMjqVgdw4DZkWlphQaWpTFBU6", # В рабочий полдень
        #     # "PLnPDytUjzMjoitAJlTHBEvAIVoV3iQUU-", # Ганапольское радио
        # ]
        max_videos = 50  # Max qty of videos to show

[menu]
    [[menu.top]]
        name = "YouTube"
        weight = 4
        identifier = "youtube"
        url = "/youtube/"

    [[menu.top]]
        name = "Donate"
        weight = 17
        identifier = "donate"
        url = "/donate/"
    
    [[menu.legal]]
        name = "Data privacy"
        weight = 10
        identifier = "data-privacy"
        url = "/data-privacy/"
    
    [[menu.legal]]
        name = "About"
        weight = 20
        identifier = "about"
        url = "/about/"

[HTTPCache]
  [HTTPCache.cache]
    [HTTPCache.cache.for]
      excludes = ['**']
      includes = []